Hack rcS so that it runs c tests as well

diff --git a/fsroot/etc/init.d/rcS b/fsroot/etc/init.d/rcS
--- a/fsroot/etc/init.d/rcS
+++ b/fsroot/etc/init.d/rcS
@@ -1,5 +1,7 @@
 #!/bin/busybox sh
 
+trap "poweroff -f" EXIT
+
 # First set up busybox symlinks
 for fn in $(busybox --list); do
   busybox ln -s /bin/busybox /bin/${fn} 2>/dev/null
@@ -7,21 +9,26 @@ done
 
 # Mount file systems and set up networking
 mount -a
+mknod /dev/full c 1 7
 ifconfig lo up
 
 cat /etc/banner
 date
 echo
 
+# fail early on failure
+set -e
+
 # Go tests
-for t in /tests/*; do
-	$t -test.v
+for t in $(ls -1 /tests/); do
+	/tests/$t -test.v
 done
 
 # Regular tests (without special flag)
-for t in /ctests/*; do
-	$t
+cd $(mktemp -d testrun.XXXXXX)
+cp /ctests/true .
+for t in $(ls -1 /ctests/); do
+	/ctests/$t
 done
 
-# Power down the system
-poweroff -f
+cat /etc/successbanner
